version: '3'

services:
  bitcoind:
    image: btcpayserver/bitcoin:0.17.0
    environment:
      BITCOIN_NETWORK: regtest
      BITCOIN_EXTRA_ARGS: |-
        rpcuser=root
        rpcpassword=toor
        rpcport=43782
        rpcbind=0.0.0.0:43782
        rpcworkqueue=99999
    ports:
      - "43782:43782"
