name: Regtest test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: docker-compose up -d
    - run: npm i
    - run: npm run lint
    - run: npm test
